### ISSUE TITLE
Help PDF link is broken

### ISSUE THREAD

**Issue by bleds22e** [ejanalysis/ejscreen#2]
I just stumbled across your package while trying to write a module for undergraduate students, and I'm really excited to work with it! Unfortunately, the help document (PDF) link is broken, and...I really need help haha

**Comment by ejanalysis** [comment]
I'll replace that pdf when I have a chance, but all the help / documentation is also available from the RStudio console if you install the ejscreen package and then type 
?ejscreen 
or 
help(package="ejscreen") 
or you can also see it on this site that makes copies of documentation from all packages it can find: https://rdrr.io/github/ejanalysis/ejscreen/man/

**Comment by ejanalysis** [comment]
Updated pdf help manual is here: 
http://ejanalysis.github.io/ejscreen/ejscreen.pdf
